version: '3'

services:
  web:
    container_name: web
    build: .
    ports:
      - 9000:8080
    privileged: true
    volumes:
      - ./mapgram:/app
    tty: true
    stdin_open: true
    command: /bin/sh